import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sofiaPro = localFont({
  src: [
    {
      path: "../public/fonts/SofiaProRegularAz.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SofiaProBoldAz.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sofia",
});

export const metadata: Metadata = {
  title: "BYTEEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sofiaPro.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
